
function private:builddate {
   $date = Get-Date -UFormat "%A, %B %e, %Y %t %r"                                                                                                                                               
   #$csclass = 'static class BuildDate { readonly static public string sBuildDate = "'                                                                                                            
   #$csclass = $csclass + $date                                                                                                                                                                   
   #$csclass = $csclass + '"; }                                                                                                                                                                   
   #// This file is generated by the building script. '                                                                                                                                           
   #Write-Output $csclass > "KthuraLauncher/builddate.cs"                                                                                                                                        
   #$cpp = '#pragma once                                                                                                                                                                          
   #define KthuraEditorBuildDate "' + $date + '"                                                                                                                                                 
   #// This file is generated by the building script. ' # I chose a macro, rather than any other approach as a macro will never cause any serious conflict when multiple files/object call this.  
   #Write-Output $csclass | out-file -encoding ASCII "KthuraLauncher/builddate.cs"                                                                                                                
   #Write-Output $cpp | out-file -encoding ASCII "KthuraEdit/headers/builddate.hpp"                                                                                                               
   
   
   Write-Output $date  | out-file -encoding ASCII "ARF_src/ID/Build"
   
   write-host "Build date: " -nonewline -foregroundcolor yellow                                                                                                                                  
   write-host $date -foregroundcolor cyan                                                                                                                                                        

}


write-host "Building Apollo Resource File!" -forgroundcolor yellow
cd "Scyndi:/Projects/Applications/VisualStudio/VC/Apollo Game Engine/"
builddate
#pushd
#cd ARF_src
#njcr add -i . -doj -cm Store -fc Store -author "Jeroen P. Broks" -notes "zlib license unless stated otherwise in documentation" "x64/Release/Apollo Game Engine.arf"
#jcr6 add -i ARF_src -doj -cm Store -fc Store -author "Jeroen P. Broks" -notes "zlib license unless stated otherwise in documentation" "x64/Release/Apollo Game Engine.arf"
#njcr script "E:\Projects\Applications\VisualStudio\VC\Apollo Game Engine\barf.lua"
jcr6_script barf.lua
#popd
